import type { RegionData } from '@/components/UKCoverageMap';

// Default region statuses used when Supabase is unavailable.
// Kept in sync with the migration seed in supabase/migrations/004_service_regions.sql.
export const FALLBACK_REGIONS: RegionData[] = [
  { id: 'greater_manchester', name: 'Greater Manchester', status: 'active' },
  { id: 'merseyside', name: 'Merseyside', status: 'active' },
  { id: 'cheshire', name: 'Cheshire', status: 'active' },
  { id: 'lancashire', name: 'Lancashire', status: 'active' },
  { id: 'cumbria', name: 'Cumbria', status: 'active' },
  { id: 'west_yorkshire', name: 'West Yorkshire', status: 'active' },
  { id: 'south_yorkshire', name: 'South Yorkshire', status: 'active' },
  { id: 'north_yorkshire', name: 'North Yorkshire', status: 'active' },
  { id: 'derbyshire', name: 'Derbyshire', status: 'active' },
  { id: 'nottinghamshire', name: 'Nottinghamshire', status: 'active' },
  { id: 'west_midlands_met', name: 'West Midlands', status: 'active' },
  { id: 'staffordshire', name: 'Staffordshire', status: 'active' },
  { id: 'wales', name: 'Wales', status: 'active' },
  { id: 'teesside', name: 'Teesside', status: 'coming_soon' },
  { id: 'tyne_and_wear', name: 'Tyne and Wear', status: 'coming_soon' },
  { id: 'county_durham', name: 'County Durham', status: 'coming_soon' },
  { id: 'northumberland', name: 'Northumberland', status: 'coming_soon' },
  { id: 'east_riding', name: 'East Riding', status: 'coming_soon' },
  { id: 'lincolnshire', name: 'Lincolnshire', status: 'coming_soon' },
  { id: 'leicestershire', name: 'Leicestershire', status: 'coming_soon' },
  { id: 'northamptonshire', name: 'Northamptonshire', status: 'coming_soon' },
  { id: 'shropshire', name: 'Shropshire', status: 'coming_soon' },
  { id: 'warwickshire', name: 'Warwickshire', status: 'coming_soon' },
  { id: 'herefordshire', name: 'Herefordshire', status: 'coming_soon' },
  { id: 'worcestershire', name: 'Worcestershire', status: 'coming_soon' },
  { id: 'norfolk', name: 'Norfolk', status: 'coming_soon' },
  { id: 'suffolk', name: 'Suffolk', status: 'coming_soon' },
  { id: 'essex', name: 'Essex', status: 'coming_soon' },
  { id: 'cambridgeshire', name: 'Cambridgeshire', status: 'coming_soon' },
  { id: 'hertfordshire', name: 'Hertfordshire', status: 'coming_soon' },
  { id: 'bedfordshire', name: 'Bedfordshire', status: 'coming_soon' },
  { id: 'london', name: 'London', status: 'coming_soon' },
  { id: 'kent', name: 'Kent', status: 'coming_soon' },
  { id: 'surrey', name: 'Surrey', status: 'coming_soon' },
  { id: 'east_sussex', name: 'East Sussex', status: 'coming_soon' },
  { id: 'west_sussex', name: 'West Sussex', status: 'coming_soon' },
  { id: 'hampshire', name: 'Hampshire', status: 'coming_soon' },
  { id: 'berkshire', name: 'Berkshire', status: 'coming_soon' },
  { id: 'buckinghamshire', name: 'Buckinghamshire', status: 'coming_soon' },
  { id: 'oxfordshire', name: 'Oxfordshire', status: 'coming_soon' },
  { id: 'isle_of_wight', name: 'Isle of Wight', status: 'coming_soon' },
  { id: 'devon', name: 'Devon', status: 'coming_soon' },
  { id: 'cornwall', name: 'Cornwall', status: 'coming_soon' },
  { id: 'somerset', name: 'Somerset', status: 'coming_soon' },
  { id: 'dorset', name: 'Dorset', status: 'coming_soon' },
  { id: 'wiltshire', name: 'Wiltshire', status: 'coming_soon' },
  { id: 'gloucestershire', name: 'Gloucestershire', status: 'coming_soon' },
  { id: 'bristol', name: 'Bristol', status: 'coming_soon' },
  { id: 'scotland', name: 'Scotland', status: 'coming_soon' },
  { id: 'northern_ireland', name: 'Northern Ireland', status: 'coming_soon' },
];
